# Generated by Django 4.2 on 2024-05-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_category_imagescategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.TextField(max_length=500, unique=True, verbose_name='Ссылка на картинку'),
        ),
    ]
